In [1]:
import numpy as np

In [2]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [3]:
np.save('myarray', arr) # Save regular numpy array

In [4]:
arr = np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

In [5]:
arr = np.load('myarray.npy')
arr

array([0, 1, 2, 3, 4])

In [6]:
arr1 = np.load('myarray.npy')
arr1

array([0, 1, 2, 3, 4])

In [7]:
arr2 = np.arange(10)
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.savez('ziparray.npz', x=arr1, y=arr2) # Save zip

In [9]:
arr_archive = np.load('ziparray.npz')
arr_archive

In [10]:
arr_archive['x']

array([0, 1, 2, 3, 4])

In [11]:
arr_archive['y']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
np.savetxt('textarrayfile.txt', matrix, delimiter=';') # Save text file

In [14]:
arr = np.loadtxt('textarrayfile.txt', delimiter=';')
arr

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])